# AUTO-GENERATED from data/operators_verified.json — do not edit by hand.
# Generated: 2026-08-05T08:04:02.372445+00:00
# Source summary: {'total_library_declared': 75, 'total_live': 6, 'total_verified': 6, 'total_ghost': 69, 'total_missing': 0, 'total_known_ghosts': 17}

"""Ghost operators: names the expression parser accepts but that are NOT real WQ functions; substitute with verified equivalents."""

GHOST_OPERATORS = [
    "abs",
    "bucket",
    "days_from_last_change",
    "densify",
    "divide",
    "group_backfill",
    "group_max",
    "group_mean",
    "group_median",
    "group_min",
    "group_neutralize",
    "group_normalize",
    "group_percentage",
    "group_rank",
    "group_vector_proj",
    "group_zscore",
    "hump",
    "jump_decay",
    "last_diff_value",
    "log",
    "max",
    "min",
    "multiply",
    "nan_mask",
    "neutralize",
    "power",
    "rank_by_side",
    "s_log_1p",
    "sigmoid",
    "sign",
    "signed_power",
    "sqrt",
    "tanh",
    "trade_when",
    "ts_av_diff",
    "ts_backfill",
    "ts_co_kurtosis",
    "ts_co_skewness",
    "ts_corr",
    "ts_covariance",
    "ts_decay_exp_window",
    "ts_decay_linear",
    "ts_delay",
    "ts_delta_limit",
    "ts_entropy",
    "ts_ir",
    "ts_kurtosis",
    "ts_max",
    "ts_max_diff",
    "ts_median",
    "ts_min",
    "ts_min_max_cps",
    "ts_min_max_diff",
    "ts_partial_corr",
    "ts_percentage",
    "ts_quantile",
    "ts_rank",
    "ts_regression",
    "ts_returns",
    "ts_skewness",
    "ts_std_dev",
    "ts_sum",
    "ts_zscore",
    "vec_avg",
    "vec_choose",
    "vec_max",
    "vec_min",
    "vec_norm",
    "vec_sum"
]
