# -*- coding: utf-8 -*-
"""基础骨架库（12 族 + 扩展族）。

从 skeletons.py 拆分而来，只包含骨架数据定义，无逻辑代码。
"""

_EPS_SMALL = "0.0001"
_EPS_VOL = "0.001"

SKELETONS = [
    {
        "id": "cs_rel.rank_diff",
        "family": "cs_rel",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "rank({x}) - rank({y})",
        "description": "两字段截面 rank 差（相对强弱/预期修正差）",
    },
    {
        "id": "cs_rel.group_rank",
        "family": "cs_rel",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_rank({x}, subindustry)",
        "description": "行业中性化截面 rank（剔除行业 beta）",
    },
    {
        "id": "ts_chg.delta",
        "family": "ts_chg",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_delta({x}, {W}))",
        "description": "字段 {W} 日变化量的截面 rank（边际变化/修正方向）",
    },
    {
        "id": "ts_chg.rel_chg",
        "family": "ts_chg",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank({x} / (ts_mean({x}, {W}) + " + _EPS_SMALL + ") - 1)",
        "description": "相对自身 {W} 日均值的偏离（均值回归/上修幅度）",
    },
    {
        "id": "anomaly.zscore",
        "family": "anomaly",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_zscore({x}, {W}))",
        "description": "字段 {W} 日 z-score 的截面 rank（异常冲击检测）",
    },
    {
        "id": "anomaly.manual_z",
        "family": "anomaly",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(({x} - ts_mean({x}, {W})) / (ts_std_dev({x}, {W}) + " + _EPS_SMALL + "))",
        "description": "手写 z-score（ts_zscore 不存在时的等价替代）",
    },
    {
        "id": "decay.linear",
        "family": "decay",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_decay_linear({x}, {W}))",
        "description": "{W} 日线性衰减加权（近期信息权重更高，降噪）",
    },
    {
        "id": "vol_adj.sharpe_like",
        "family": "vol_adj",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank({x}) / (ts_std_dev(returns, {W}) + " + _EPS_VOL + ")",
        "description": "截面 rank 除以波动率（低风险调整，类 Sharpe 加权）",
    },
    {
        "id": "group_neut.industry",
        "family": "group_neut",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_neutralize({x}, subindustry)",
        "description": "行业中性化（剔除行业均值，保留截面相对强弱）",
    },
    {
        "id": "group_zscore.industry",
        "family": "group_zscore",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_zscore({x}, subindustry)",
        "description": "行业内 z-score（剔除行业 beta，保留组内相对位置）",
    },
    {
        "id": "ts_corr.price_volume",
        "family": "ts_corr",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_corr(rank({x}), rank({y}), {W})",
        "description": "两字段 {W} 日 rank 相关（量价协同/背离检测）",
    },
    {
        "id": "event_gate.trade_when",
        "family": "event_gate",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "trade_when(less(ts_count_nans({x}, {W}), {W}), rank({x}), 0)",
        "description": "事件门控（{W} 日窗口内至少一天有数据才交易 rank({x})，无事件则空仓）",
    },
    {
        "id": "conditional.if_else",
        "family": "conditional",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "if_else(greater({x}, 0), rank({x}), rank({y}))",
        "description": "条件组合（{x} 为正时取 rank({x})，否则取 rank({y})）",
    },
    {
        "id": "momentum_peak.arg_max",
        "family": "momentum_peak",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_arg_max({x}, {W}))",
        "description": "{W} 日内峰值位置 rank（峰值越近尾部=趋势仍在强化）",
    },
    {
        "id": "outlier.winsorize",
        "family": "outlier",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "rank(winsorize({x}, std=4))",
        "description": "4-sigma 截尾后 rank（压制极端值主导，稳健化）",
    },
    {
        "id": "ts_regression.beta",
        "family": "ts_regression",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_regression({y}, {x}, {W}))",
        "description": "{y} 对 {x} 的 {W} 日回归敏感度 rank（弹性/联动检测）",
    },
    # ---- 2026-09-13 骨架库扩充（16→30，按机制族成倍扩展）----
    # 新增族：ratio_eff / accel / trend_cons / quality / quantile_dist / smooth /
    #         tail_trim / rank_mo / group_scale / group_cart。
    # 全部算子已过 live known_ops（103）核验；ratio_eff 为 2 字段（field2 必填）。
    # 同日修正两个历史坏骨架：decay_linear → ts_decay_linear、ts_count → ts_count_nans
    # （原算子名不在 live 白名单，产物会被闸4/平台拦）。
    {
        "id": "ratio_eff.flow_stock",
        "family": "ratio_eff",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "rank(divide({x}, {y} + " + _EPS_SMALL + "))",
        "description": "流量÷存量效率比 rank（经营效率/强度比，需单一比率叙事）",
    },
    {
        "id": "accel.delta_of_delta",
        "family": "accel",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_delta(ts_delta({x}, {W}), {W}))",
        "description": "变化的加速度（二阶变化，改善在加速=正）",
    },
    {
        "id": "accel.delta_zscore",
        "family": "accel",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_zscore(ts_delta({x}, {W}), {W}))",
        "description": "变化量的标准化强度（变化相对自身历史波动，异常变化检测）",
    },
    {
        "id": "trend_cons.ma_ratio",
        "family": "trend_cons",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(divide(ts_mean({x}, {W}), ts_mean({x}, {W2}) + " + _EPS_SMALL + "))",
        "description": "快慢均线比（短窗/长窗均值，趋势强度与方向；W2=3×W 自动）",
    },
    {
        "id": "quality.ts_ir",
        "family": "quality",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_ir({x}, {W}))",
        "description": "{W} 日时序信息比 rank（均值/波动，信号质量）",
    },
    {
        "id": "vol_adj.self_vol",
        "family": "vol_adj",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(divide({x}, ts_std_dev({x}, {W}) + " + _EPS_VOL + "))",
        "description": "字段÷自身波动率（稳定性调整：高波动字段降权）",
    },
    {
        "id": "quantile_dist.ts_q_rank",
        "family": "quantile_dist",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_quantile({x}, {W}, driver=\"gaussian\"))",
        "description": "{W} 日分位正态化后截面 rank（厚尾字段稳健化）",
    },
    {
        "id": "anomaly.av_diff",
        "family": "anomaly",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "rank(ts_av_diff({x}, {W}))",
        "description": "对 {W} 日均值的绝对偏离 rank（异常偏离幅度）",
    },
    {
        "id": "smooth.hump",
        "family": "smooth",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "hump(rank({x}), hump=0.01)",
        "description": "变动幅度压制 rank（低换手稳健版，TVR 墙）",
    },
    {
        "id": "smooth.target_tvr",
        "family": "smooth",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "ts_target_tvr_hump(rank({x}), target_tvr=0.15)",
        "description": "目标换手率自适应平滑 rank（对准 TVR≈15%）",
    },
    {
        "id": "tail_trim.center",
        "family": "tail_trim",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "tail(rank({x}), lower=0.1, upper=0.9, newval=0.5)",
        "description": "中段压平只留两端极端信念（10/90 分位外保留）",
    },
    {
        "id": "rank_mo.rank_delta",
        "family": "rank_mo",
        "n_fields": 1,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_delta(rank({x}), {W})",
        "description": "截面排名的时序变化（相对地位爬升/下降）",
    },
    {
        "id": "group_scale.industry",
        "family": "group_scale",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_scale({x}, subindustry)",
        "description": "行业内 0-1 缩放（跨行业可比，与 group_zscore 互补）",
    },
    {
        "id": "group_cart.dual",
        "family": "group_cart",
        "n_fields": 1,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_rank({x}, group_cartesian_product(densify(sector), densify(subindustry)))",
        "description": "双维分组 rank（sector×subindustry 交乘，更细的同类可比）",
    },
    # ---- 2026-09-17 经济学概念骨架（option40 ideas 固化，解决结构同质化）----
    {
        "id": "econ_vol_surface.vega_premium_residual",
        "family": "econ_vol_surface",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_zscore(divide({x}, multiply({y}, {z})), subindustry)",
        "description": "Vega-normalized premium residual：期权价格 per unit vol-risk per unit IV，相对子行业均值（vol-risk-premium mispricing）",
        "mechanism": "premium/vega/IV 剥离共同波动水平，留下特质 richness；买方支付保护/上行溢价，均值回归",
    },
    {
        "id": "econ_vol_surface.gamma_delta_tension",
        "family": "econ_vol_surface",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_rank(divide({x}, add({y}, {z})), subindustry)",
        "description": "Convexity-per-directional-exposure tension：gamma(365d) / (delta(91d) + IV(91d))，低 delta 高 convexity = crash-or-jump pricing",
        "mechanism": "gamma/delta 比率定价离散大移动（event/pinning risk），股票尚未实现；组内相对凸性需求",
    },
    {
        "id": "econ_vol_surface.delta_ladder_slope",
        "family": "econ_vol_surface",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_zscore(subtract(divide({x}, {z}), divide({y}, {z})), subindustry)",
        "description": "Delta-ladder slope：547d/30d delta - 91d/30d delta，期限结构方向暴露斜率（隐含长期漂移预期）",
        "mechanism": "长 tenor delta 嵌入 drift/borrow/repurchase 预期，短 tenor 仅 immediate direction；斜率=长期漂移净短期移动",
    },
    {
        "id": "econ_vol_surface.vol_carry",
        "family": "econ_vol_surface",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_zscore(divide({x}, add(abs({y}), ts_std_dev({y}, 66))), subindustry)",
        "description": "Vol carry：theta(30d) / (|vega(30d)| + std(vega,66))，时间衰减成本 per unit vol risk（拥挤对冲需求均值回归）",
        "mechanism": "theta/vega 是 vol-carry 盈亏平衡；高 carry vs 子行业 = 拥挤对冲，吸引卖方均值回归",
    },
    {
        "id": "econ_sentiment.dispersion_skew",
        "family": "econ_sentiment",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract({x}, {y}), add({z}, abs({x})))",
        "description": "Extreme-range fear intensity normalized：(neg_max - neg_min) / (neg_std + |neg_mean|)，极端负面情绪范围/波动",
        "mechanism": "负面情绪极端范围相对其波动和均值的水平，捕捉恐慌强度而非方向",
    },
    {
        "id": "econ_sentiment.mean_median_skew",
        "family": "econ_sentiment",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract({x}, {y}), add(ts_backfill({z}, 22), ts_std_dev({x}, 22)))",
        "description": "Mean-median skew of sentiment tone：(neg_mean - neg_median) / (neg_std + ts_std(neg_mean,22))，情绪均值-中位数偏度/波动",
        "mechanism": "均值-中位数差捕捉情绪分布偏斜，标准化后跨股票可比",
    },
    {
        "id": "econ_option.put_call_skew",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "trade_when(greater({x}, {y}), subtract(divide(subtract({x}, {y}), add({x}, {y})), divide(subtract({z}, {w}), add({z}, {w}))), -1)",
        "description": "Put-minus-call skew steepness：30d put-call spread normalized - 180d anchor，front-end crash premium 期限结构斜率",
        "mechanism": "短期 put-call 偏度相对长期锚点的陡峭化，捕捉未 repriced 到长期限的崩盘恐惧",
    },
    {
        "id": "econ_option.term_structure_butterfly",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(subtract({y}, {x}), subtract({z}, {y}))",
        "description": "Term-structure curvature (butterfly)：mid-tenor hump over wings (91d - 60d) - (273d - 91d)，波动率曲线凸性/日历价差风险",
        "mechanism": "期限结构凸性是日历价差供需的定价，纯二阶差分保持结构性",
    },
    {
        "id": "econ_option.gamma_theta_ratio",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Carry-versus-convexity intensity：gamma(60d)/theta(60d) - gamma(91d)/theta(91d)，front vs mid tenor 凸性性价比",
        "mechanism": "gamma/theta 是 convexity per unit carry 的价格；front tenor 支付更多 convexity = 对冲需求，预测 IV 均值回归",
    },
    {
        "id": "econ_option.vega_delta_leverage",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "vector_neut(divide({x}, {y}), {z})",
        "description": "Vega-per-delta leverage residualized：vega(91d)/delta(91d) orthogonalized vs IV(91d)，凸性暴露融资非高波动名称",
        "mechanism": "vol exposure per unit directional exposure 衡量期权头寸杠杆；正交化 IV 剥离高波动因素",
    },
    {
        "id": "econ_option.forward_strike_moneyness",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Forward-vs-strike moneyness residual：60d forward/strike - 182d forward/strike，carry/dividend-implied forward 期限不一致",
        "mechanism": "forward/strike 是无量纲 moneyness/carry 比率；期限不一致暗示利率/股息路径定价错误",
    },
    {
        "id": "econ_option.iv_term_inversion",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract({x}, {y}), {y})",
        "description": "Implied-vol term-structure inversion：30d IV - 360d IV / 360d IV，近端压力相对水平（curve inversion）",
        "mechanism": "30d IV > 360d IV 时曲线倒挂，仅倒挂 widening（22d 前端上升签名）携带信息",
    },
    {
        "id": "econ_option.iv_change_vs_level",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "divide(ts_delta({x}, 22), ts_std_dev({x}, 66))",
        "description": "Change-vs-level in put implied vol：22d change in IV / 66d std， realized vol-of-vol scaled by level",
        "mechanism": "IV 变化相对自身历史波动，区分 regime shift 与普通波动",
    },
    {
        "id": "econ_option.delta_iv_comove",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_corr({x}, {y}, 66)",
        "description": "Delta-vol co-movement disagreement：put delta 与 IV 的 66d 相关，sticky-delta vs sticky-strike regime",
        "mechanism": "delta 与 IV 同向 = sticky-delta；背离 = skew repricing；短 tenor 与长 tenor 相关差异=局部 spot-driven vol 未确认",
    },
    {
        "id": "econ_option.cost_of_protection",
        "family": "econ_option",
        "n_fields": 5,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, multiply({y}, {z})), divide({w}, {v}))",
        "description": "Cost-of-protection intensity：put premium / (vega × strike) 60d - 182d，短期保险相对长期保险昂贵度（拥挤下行对冲）",
        "mechanism": "premium/vega/strike 是 scale-free price-per-vol-point；短期保险昂贵 = 拥挤对冲，通常 over-priced",
    },
    {
        "id": "econ_option.strike_ladder_geometry",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(divide(subtract({x}, {y}), {y}), {z})",
        "description": "Listed expected move vs strike geometry：(152d strike - 547d strike)/547d strike / 60d IV，行权价阶梯相对隐含预期移动",
        "mechanism": "行权价阶梯由交易商预期分布设定；漂移远离 forward 和 IV 暗示 positioning/skew imbalance",
    },
    {
        "id": "econ_option.gamma_premium_cost",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Cost of convexity：gamma(122d)/premium(122d) - gamma(730d)/premium(730d)，convexity term premium 斜率",
        "mechanism": "gamma/premium 是 dimensionless convexity price；long-minus-short 是 convexity term premium，21d change 是 repricing",
    },
    {
        "id": "econ_option.premium_forward_cost",
        "family": "econ_option",
        "n_fields": 5,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract(divide({x}, {y}), divide({z}, {w})), {v})",
        "description": "Implied cost of optionality vs model forward：(730d premium/forward - 122d premium/forward) / delta(152d)，长期期权成本 term premium 条件化 delta",
        "mechanism": "premium/forward 剥离标的价格水平，留下 pure carry-and-variance charge；per-unit-delta 跨名称可比",
    },
    {
        "id": "econ_option.theta_gamma_efficiency",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Time-decay efficiency：theta(60d)/gamma(60d) - theta(182d)/gamma(182d)，carry bleed per unit convexity 期限结构",
        "mechanism": "theta/gamma 是每日盈亏平衡移动（convexity 成本）；短期比率远高于长期 = 近端 convexity  richly valued",
    },
    {
        "id": "econ_option.delta_curve_curvature",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(add({y}, {y}), add({x}, {z}))",
        "description": "Delta-curve curvature：2×273d delta - (152d delta + 730d delta)，方向暴露期限结构凸性/倾斜",
        "mechanism": "标准化表面 delta 期限结构凸性，捕捉表面向近端或远端倾斜",
    },
    {
        "id": "econ_option.iv_skew_velocity",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "multiply(divide(subtract({x}, {y}), {y}), sign(subtract({x}, ts_delay({x}, 22))))",
        "description": "IV term-structure inversion widening velocity：(30d IV - 360d IV)/360d IV × sign(30d IV 22d change)，倒挂扩大速度",
        "mechanism": "仅倒挂 widening（22d 前端上升签名）携带信息，分离 genuine front-end repricing 与 parallel vol shift",
    },
    {
        "id": "econ_option.front_end_vol_shock",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "vector_neut(divide({x}, {z}), divide({y}, {z}))",
        "description": "Near-tenor IV shock residualized：60d/273d IV ratio demeaned and neutralized vs 91d/273d leg，前端 vol 冲击未沿曲线传播",
        "mechanism": "交易商对前端 vol 定价对冲需求，长端跟踪宏观 vol；斜率去均值+正交化隔离短端 vol 冲击均值回归",
    },
    {
        "id": "econ_option.vol_surface_curvature",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_rank(subtract(subtract({y}, {x}), subtract({z}, {y})), 252)",
        "description": "Term-structure curvature dislocation：butterfly (91d-60d)-(273d-91d) 的 250d ts_rank，表面 dislocation vs 正常形状",
        "mechanism": "期限结构凸性是日历价差供需定价；ts_rank 捕捉 dislocation 相对自身历史",
    },
    {
        "id": "econ_option.gamma_vega_convexity",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Gamma-vega convexity intensity：gamma(30d)/vega(91d) - gamma(365d)/vega(273d)，convexity per unit vol sensitivity 期限结构",
        "mechanism": "短期 put 高 gamma/vega = 纯 convexity exposure；长期 = term-premium exposure；短长差捕捉 option risk premium 形状",
    },
    {
        "id": "econ_option.put_moneyness_term",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Put moneyness term-structure residual：122d forward/strike - 730d forward/strike，近端 put 相对远端 richness",
        "mechanism": "短期 forward/strike 高于长期 = 近端 put 相对 OTM vs 长期合约，结构性 mispricing 或对冲压力",
    },
    {
        "id": "econ_option.vol_of_vol_vs_level",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "divide(ts_std_dev({x}, 22), {z})",
        "description": "Vol-of-vol vs implied level：std(91d IV,22) / 365d IV，implied vol 已实现波动相对长期水平",
        "mechanism": "IV 自身移动速率相对长期水平；高 vol-of-vol 或短期 IV 剧变 vs 稳定 365d 锚 = 期权被快速 repricing",
    },
    {
        "id": "econ_option.put_iv_term_slope",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {z})",
        "description": "Put IV term-structure slope：30d put IV / 365d put IV，近端恐惧 vs 长期不确定性",
        "mechanism": "短期限 put IV 相对长期限的比率，捕捉 imminent event risk 与 persistent vol regime 的定价",
    },
    {
        "id": "econ_option.vega_iv_leverage",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Vega-per-IV leverage：91d vega / 91d IV，vol risk priced per unit uncertainty（cheap convexity claim vs rich vol payment）",
        "mechanism": "vega 高 IV 低 = cheap convexity claim；vega 低 IV 高 = 市场已 richly 支付 vol",
    },
    {
        "id": "econ_option.short_end_vol_curve",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_corr(subtract({x}, {y}), {z}, 66)",
        "description": "Short-end vol-curve slope crossed with long-dated convexity：122d-91d IV gap correlated with 365d gamma，短期曲线陡峭是否有真实凸性支撑",
        "mechanism": "短期 IV 斜率陡峭通常意味近端事件风险，仅当伴随长期 convexity 升高才是 durable repricing",
    },
    {
        "id": "econ_option.matched_tenor_convexity",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "group_zscore(divide({x}, abs({y})), subindustry)",
        "description": "Matched-tenor convexity per unit time decay：152d gamma / |152d theta|，static replication tension（曲率 per unit 衰减）",
        "mechanism": "gamma/theta 是 convexity received 与 time paid 的汇率；固定 152d tenor 跨名称可比，高值=大移动便宜定价",
    },
    {
        "id": "econ_option.range_noise_vs_close",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract({x}, {y}), add({x}, {y}))",
        "description": "Range-noise vs close-noise vol disagreement：(90d Parkinson vol - 90d close-to-close vol) / sum，未在收盘价中定价的日内波动",
        "mechanism": "两种 90d 风险估计器分歧 = 测量分歧而非水平赌注；归一化后跨波动 regime 可比",
    },
    {
        "id": "econ_option.vol_term_slope_persistence",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_ir(divide({x}, {z}), 66)",
        "description": "Volatility term-structure slope persistence：10d Parkinson vol / 180d vol 的 63d ts_ir，期限溢价是否持续 signed",
        "mechanism": "slope 是 level-free 原语；ts_ir 检验斜率是否持续同号（真实期限溢价 vs 一日 vol  spike）",
    },
    {
        "id": "econ_option.decay_shape_vs_vega",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "vector_neut(divide({x}, {y}), divide({z}, {w}))",
        "description": "Decay-shape vs vega-shape residual：theta 91d/730d ratio orthogonalized vs vega 60d/730d ratio，front-loaded optionality 剥离 vol 敏感性",
        "mechanism": "theta 比率衡量时间衰减前置程度（近端现金流期权性），vega 比率衡量 vol 敏感性位置；正交化剥离高波动名称因素",
    },
    {
        "id": "econ_option.front_end_repricing_decoupled",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "trade_when(less(ts_corr(ts_delta({x}, 5), ts_delta({z}, 5), 66), 0.3), divide(subtract({x}, {z}), {z}), -1)",
        "description": "Front-end vol repricing decoupled from long end：30d/365d vol spread scaled by long end，当两端 5d change 相关 <0.3 时交易",
        "mechanism": "短期信息到达；前端 repricing 与长端脱钩时，隔离名称特定近端不确定性未沿曲线传播",
    },
    {
        "id": "econ_option.put_iv_slope_disagreement",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({y}, {z}))",
        "description": "Put IV term-structure slope disagreement：60d/90d put IV - 90d/720d put IV，90d belly kink 而非简单水平赌注",
        "mechanism": "短期限与长期限 ATM put vol 比率隔离曲线凸性/斜率；陡峭近端 = 近端对冲需求均值回归",
    },
    {
        "id": "econ_option.delta_convexity_disagreement",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "trade_when(greater(ts_returns({z}, 22), 0), subtract(ts_returns({x}, 22), ts_returns({y}, 22)), -1)",
        "description": "Delta-convexity disagreement：152d delta 22d return - 182d gamma 22d return，方向流动无凸性需求伴随（更可能反转）",
        "mechanism": "delta 移动但 gamma/theta-priced convexity 不动 = 对冲/流动性流动而非 vol 分布 repricing，更可能反转",
    },
    {
        "id": "econ_option.iv_skew_co_movement",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": True,
        "sign_allowed": True,
        "template": "subtract(ts_corr({x}, {y}, 66), ts_corr({z}, {w}, 66))",
        "description": "Put delta-IV skew co-movement：182d delta-IV corr - 91d delta-IV corr，sticky-delta vs sticky-strike regime shift 期限差异",
        "mechanism": "delta 与 IV 同向 = sticky-delta；背离 = skew repricing；短期限与长期限相关差异 = 局部 spot-driven vol 未确认",
    },
    {
        "id": "econ_option.gamma_per_dollar_premium",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Cost of convexity per dollar：gamma(122d) / premium(122d)，dimensionless convexity price（曲率 per 美元权利金）",
        "mechanism": "gamma/premium 是跨名称可比的凸性价格；高值=市场收取的曲率昂贵",
    },
    {
        "id": "econ_option.optionality_cost_vs_forward",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Implied cost of optionality vs forward：730d premium/forward - 122d premium/forward，长期期权成本 term premium",
        "mechanism": "premium/forward 剥离标的价格水平，留下 pure carry-and-variance charge；长期限斜率是长期期权成本",
    },
    {
        "id": "econ_option.theta_per_gamma_break_even",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Theta per gamma break-even：theta(60d) / gamma(60d)，每日盈亏平衡移动（convexity 成本）",
        "mechanism": "theta/gamma 是期权每日需要的移动以盈亏平衡，即 convexity 的成本",
    },
    {
        "id": "econ_option.delta_moneyness_profile",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract({z}, {x}), add({z}, {x}))",
        "description": "Delta-curve monotone tilt：(730d delta - 152d delta) / (730d delta + 152d delta)，方向暴露期限结构单调倾斜",
        "mechanism": "标准化表面 delta 期限结构单调倾斜，捕捉表面向近端或远端倾斜",
    },
    {
        "id": "econ_option.iv_front_end_shock",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_av_diff(divide({x}, {z}), 66)",
        "description": "Near-tenor IV shock change-vs-own-mean：60d/273d IV ratio 66d 去均值，前端 vol 冲击相对自身历史",
        "mechanism": "斜率比率是持续水平因素，去均值后隔离短端 vol 冲击均值回归",
    },
    {
        "id": "econ_option.vol_curve_butterfly_dislocation",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_av_diff(subtract(subtract({y}, {x}), subtract({z}, {y})), 22)",
        "description": "Term-structure curvature dislocation 22d：butterfly (91d-60d)-(273d-91d) 22d 去均值，表面 dislocation 短期变化",
        "mechanism": "期限结构凸性 22d 变化，捕捉表面 dislocation 相对自身近期历史",
    },
    {
        "id": "econ_option.carry_convexity_front_mid",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Carry-versus-convexity front-mid spread：gamma(60d)/theta(60d) - gamma(91d)/theta(91d)，front vs mid tenor 凸性性价比差异",
        "mechanism": "gamma/theta 是 convexity per unit carry 价格；front tenor 支付更多 convexity = 对冲需求，预测 IV 均值回归",
    },
    {
        "id": "econ_option.vega_delta_leverage_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Vega-per-delta leverage raw：91d vega / 91d delta，vol exposure per unit directional exposure（期权头寸杠杆）",
        "mechanism": "vol exposure per unit directional exposure 衡量期权头寸杠杆；与 IV 水平相关（两者均随 vol 缩放）",
    },
    {
        "id": "econ_option.strike_forward_moneyness",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract({x}, {z}), {z})",
        "description": "Strike vs forward moneyness：152d strike - 182d forward / 182d forward，行权价相对远期价格位置",
        "mechanism": "行权价相对远期价格的位置，捕捉交易商预期分布设定与实际 forward 的偏离",
    },
    {
        "id": "econ_option.gamma_theta_matched_tenor",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, abs({y}))",
        "description": "Gamma per unit time decay matched tenor：152d gamma / |152d theta|，convexity received 与 time paid 汇率",
        "mechanism": "gamma/theta 是 convexity received 与 time paid 的汇率；固定 152d tenor 跨名称可比",
    },
    {
        "id": "econ_option.parkinson_vs_close_vol",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Parkinson vs close-to-close vol ratio：90d Parkinson vol / 90d close-to-close vol，高低价范围噪声与收盘噪声比率",
        "mechanism": "两种 90d 风险估计器比率，捕捉未在收盘价中定价的日内波动/隔夜跳空不对称",
    },
    {
        "id": "econ_option.vol_slope_short_long",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Volatility term-structure slope short/long：10d Parkinson vol / 180d vol，短期限相对长期限波动率水平",
        "mechanism": "短期限 Parkinson vol 相对长期限的比率，捕捉市场定价的近端风险 vs 远端风险",
    },
    {
        "id": "econ_option.theta_vega_front_loaded",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Theta front-loaded ratio：91d theta / 730d theta，时间衰减前置程度（近端现金流期权性）",
        "mechanism": "theta 91d/730d 比率衡量时间衰减前置程度，捕捉近端现金流期权性 vs 远端",
    },
    {
        "id": "econ_option.vega_front_loaded",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Vega front-loaded ratio：60d vega / 730d vega，vol 敏感性前置程度",
        "mechanism": "vega 60d/730d 比率衡量 vol 敏感性位置，捕捉前端 vol 暴露 vs 远端",
    },
    {
        "id": "econ_option.iv_30_360_inversion",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract({x}, {y})",
        "description": "IV 30d-360d absolute inversion：30d IV - 360d IV，近端压力绝对水平（curve inversion level）",
        "mechanism": "30d IV > 360d IV 时曲线倒挂，绝对水平捕捉近端压力程度",
    },
    {
        "id": "econ_option.put_iv_30_365_slope",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Put IV 30d/365d slope：30d put IV / 365d put IV，近端恐惧 vs 长期不确定性比率",
        "mechanism": "短期限 put IV 相对长期限的比率，捕捉 imminent event risk 与 persistent vol regime 的定价",
    },
    {
        "id": "econ_option.vega_91_365_leverage",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Vega 91d/365d leverage：91d vega / 365d vega，vol 敏感性期限结构",
        "mechanism": "91d vega 相对 365d vega 的比率，捕捉 vol 敏感性期限结构",
    },
    {
        "id": "econ_option.gamma_30_365_convexity",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Gamma 30d/365d convexity：30d gamma / 365d gamma，convexity 期限结构",
        "mechanism": "30d gamma 相对 365d gamma 的比率，捕捉 convexity 期限结构",
    },
    {
        "id": "econ_option.forward_122_730_moneyness",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Forward 122d/730d moneyness：122d forward / 730d forward，远期价格期限结构",
        "mechanism": "122d forward 相对 730d forward 的比率，捕捉远期价格期限结构",
    },
    {
        "id": "econ_option.iv_91_365_vol_of_vol",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "divide(ts_std_dev({x}, 22), {y})",
        "description": "IV 91d vol-of-vol vs 365d level：std(91d IV,22) / 365d IV，implied vol 已实现波动相对长期水平",
        "mechanism": "91d IV 自身 22d 波动相对 365d IV 水平，捕捉 IV 移动速率",
    },
    {
        "id": "econ_option.delta_182_91_skew",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_corr({x}, {y}, 22)",
        "description": "Delta 182d-IV 91d skew co-movement 22d：182d delta 与 91d IV 的 22d 相关，短期 sticky-delta vs sticky-strike",
        "mechanism": "182d delta 与 91d IV 的 22d 相关，捕捉短期 sticky-delta vs sticky-strike regime",
    },
    {
        "id": "econ_option.premium_122_730_cost",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Premium 122d/730d cost：122d premium / 730d premium，权利金期限结构",
        "mechanism": "122d premium 相对 730d premium 的比率，捕捉权利金期限结构",
    },
    {
        "id": "econ_option.theta_60_182_efficiency",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Theta 60d/182d efficiency：60d theta / 182d theta，时间衰减期限结构",
        "mechanism": "60d theta 相对 182d theta 的比率，捕捉时间衰减期限结构",
    },
    {
        "id": "econ_option.delta_152_730_profile",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Delta 152d/730d profile：152d delta / 730d delta，方向暴露期限结构",
        "mechanism": "152d delta 相对 730d delta 的比率，捕捉方向暴露期限结构",
    },
    {
        "id": "econ_option.iv_60_273_shock",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_av_diff(divide({x}, {y}), 66)",
        "description": "IV 60d/273d shock 66d：60d IV / 273d IV 66d 去均值，前端 vol 冲击相对自身历史",
        "mechanism": "60d IV 相对 273d IV 的比率 66d 去均值，捕捉前端 vol 冲击",
    },
    {
        "id": "econ_option.vol_91_60_273_butterfly",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(subtract({y}, {x}), subtract({z}, {y}))",
        "description": "Vol 91d-60d-273d butterfly：(91d vol - 60d vol) - (273d vol - 91d vol)，波动率曲线凸性",
        "mechanism": "91d-60d-273d 波动率曲线凸性，捕捉日历价差供需定价",
    },
    {
        "id": "econ_option.gamma_theta_60_91_spread",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Gamma-theta 60d-91d spread：gamma(60d)/theta(60d) - gamma(91d)/theta(91d)，front vs mid tenor 凸性性价比",
        "mechanism": "gamma/theta 是 convexity per unit carry 价格；front tenor 支付更多 convexity = 对冲需求",
    },
    {
        "id": "econ_option.vega_delta_91_leverage",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Vega-delta 91d leverage：91d vega / 91d delta，vol exposure per unit directional exposure",
        "mechanism": "91d vega 相对 91d delta 的比率，捕捉期权头寸杠杆",
    },
    {
        "id": "econ_option.strike_152_547_geometry",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract({x}, {y}), {y})",
        "description": "Strike 152d-547d geometry：(152d strike - 547d strike) / 547d strike，行权价阶梯几何",
        "mechanism": "152d strike 相对 547d strike 的比率，捕捉行权价阶梯几何",
    },
    {
        "id": "econ_option.gamma_premium_122_cost",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Gamma-premium 122d cost：122d gamma / 122d premium，convexity per dollar",
        "mechanism": "122d gamma 相对 122d premium 的比率，捕捉 convexity per dollar",
    },
    {
        "id": "econ_option.premium_forward_730_cost",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Premium-forward 730d cost：730d premium / 730d forward，长期期权成本",
        "mechanism": "730d premium 相对 730d forward 的比率，捕捉长期期权成本",
    },
    {
        "id": "econ_option.theta_gamma_60_break_even",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Theta-gamma 60d break-even：60d theta / 60d gamma，每日盈亏平衡移动",
        "mechanism": "60d theta 相对 60d gamma 的比率，捕捉每日盈亏平衡移动",
    },
    {
        "id": "econ_option.delta_273_152_730_curvature",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(add({y}, {y}), add({x}, {z}))",
        "description": "Delta 273d-152d-730d curvature：2×273d delta - (152d delta + 730d delta)，方向暴露期限结构凸性",
        "mechanism": "273d-152d-730d delta 期限结构凸性，捕捉表面向近端或远端倾斜",
    },
    {
        "id": "econ_option.iv_30_360_velocity",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "multiply(divide(subtract({x}, {y}), {y}), sign(subtract({x}, ts_delay({x}, 22))))",
        "description": "IV 30d-360d velocity：(30d IV - 360d IV)/360d IV × sign(30d IV 22d change)，倒挂扩大速度",
        "mechanism": "仅倒挂 widening（22d 前端上升签名）携带信息，分离 genuine front-end repricing 与 parallel vol shift",
    },
    {
        "id": "econ_option.iv_60_273_neut",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "vector_neut(divide({x}, {z}), divide({y}, {z}))",
        "description": "IV 60d/273d neutralized：60d/273d IV ratio neutralized vs 91d/273d leg，前端 vol 冲击正交化",
        "mechanism": "60d/273d IV 比率正交化 91d/273d 腿，隔离短端 vol 冲击",
    },
    {
        "id": "econ_option.vol_butterfly_250_rank",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_rank(subtract(subtract({y}, {x}), subtract({z}, {y})), 252)",
        "description": "Vol butterfly 250d rank：(91d-60d)-(273d-91d) 250d ts_rank，表面 dislocation 长期排名",
        "mechanism": "期限结构凸性 250d ts_rank，捕捉表面 dislocation 相对长期历史",
    },
    {
        "id": "econ_option.gamma_vega_30_91_convexity",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Gamma-vega 30d/91d convexity：30d gamma / 91d vega，convexity per unit vol sensitivity",
        "mechanism": "30d gamma 相对 91d vega 的比率，捕捉 convexity per unit vol sensitivity",
    },
    {
        "id": "econ_option.forward_strike_122_moneyness",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Forward-strike 122d moneyness：122d forward / 122d strike，moneyness/carry 比率",
        "mechanism": "122d forward 相对 122d strike 的比率，捕捉 moneyness/carry 比率",
    },
    {
        "id": "econ_option.iv_91_365_std",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "divide(ts_std_dev({x}, 22), {y})",
        "description": "IV 91d std vs 365d level：std(91d IV,22) / 365d IV，implied vol 已实现波动相对长期水平",
        "mechanism": "91d IV 自身 22d 波动相对 365d IV 水平，捕捉 IV 移动速率",
    },
    {
        "id": "econ_option.delta_iv_182_91_corr",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_corr({x}, {y}, 66)",
        "description": "Delta-IV 182d-91d corr 66d：182d delta 与 91d IV 的 66d 相关，sticky-delta vs sticky-strike regime",
        "mechanism": "182d delta 与 91d IV 的 66d 相关，捕捉 sticky-delta vs sticky-strike regime",
    },
    {
        "id": "econ_option.premium_122_730_slope",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Premium 122d/730d slope：122d premium / 730d premium，权利金期限结构斜率",
        "mechanism": "122d premium 相对 730d premium 的比率，捕捉权利金期限结构斜率",
    },
    {
        "id": "econ_option.theta_60_182_ratio",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Theta 60d/182d ratio：60d theta / 182d theta，时间衰减期限结构比率",
        "mechanism": "60d theta 相对 182d theta 的比率，捕捉时间衰减期限结构比率",
    },
    {
        "id": "econ_option.delta_152_730_ratio",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Delta 152d/730d ratio：152d delta / 730d delta，方向暴露期限结构比率",
        "mechanism": "152d delta 相对 730d delta 的比率，捕捉方向暴露期限结构比率",
    },
    {
        "id": "econ_option.iv_60_273_av_diff",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_av_diff(divide({x}, {y}), 66)",
        "description": "IV 60d/273d av-diff 66d：60d IV / 273d IV 66d 去均值，前端 vol 冲击相对自身历史",
        "mechanism": "60d IV 相对 273d IV 的比率 66d 去均值，捕捉前端 vol 冲击",
    },
    {
        "id": "econ_option.vol_91_60_273_butterfly_raw",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(subtract({y}, {x}), subtract({z}, {y}))",
        "description": "Vol 91d-60d-273d butterfly raw：(91d vol - 60d vol) - (273d vol - 91d vol)，波动率曲线凸性",
        "mechanism": "91d-60d-273d 波动率曲线凸性，捕捉日历价差供需定价",
    },
    {
        "id": "econ_option.gamma_theta_60_91_spread_raw",
        "family": "econ_option",
        "n_fields": 4,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(divide({x}, {y}), divide({z}, {w}))",
        "description": "Gamma-theta 60d-91d spread raw：gamma(60d)/theta(60d) - gamma(91d)/theta(91d)，front vs mid tenor 凸性性价比",
        "mechanism": "gamma/theta 是 convexity per unit carry 价格；front tenor 支付更多 convexity = 对冲需求",
    },
    {
        "id": "econ_option.vega_delta_91_leverage_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Vega-delta 91d leverage raw：91d vega / 91d delta，vol exposure per unit directional exposure",
        "mechanism": "91d vega 相对 91d delta 的比率，捕捉期权头寸杠杆",
    },
    {
        "id": "econ_option.strike_152_547_geometry_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide(subtract({x}, {y}), {y})",
        "description": "Strike 152d-547d geometry raw：(152d strike - 547d strike) / 547d strike，行权价阶梯几何",
        "mechanism": "152d strike 相对 547d strike 的比率，捕捉行权价阶梯几何",
    },
    {
        "id": "econ_option.gamma_premium_122_cost_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Gamma-premium 122d cost raw：122d gamma / 122d premium，convexity per dollar",
        "mechanism": "122d gamma 相对 122d premium 的比率，捕捉 convexity per dollar",
    },
    {
        "id": "econ_option.premium_forward_730_cost_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Premium-forward 730d cost raw：730d premium / 730d forward，长期期权成本",
        "mechanism": "730d premium 相对 730d forward 的比率，捕捉长期期权成本",
    },
    {
        "id": "econ_option.theta_gamma_60_break_even_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Theta-gamma 60d break-even raw：60d theta / 60d gamma，每日盈亏平衡移动",
        "mechanism": "60d theta 相对 60d gamma 的比率，捕捉每日盈亏平衡移动",
    },
    {
        "id": "econ_option.delta_273_152_730_curvature_raw",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "subtract(add({y}, {y}), add({x}, {z}))",
        "description": "Delta 273d-152d-730d curvature raw：2×273d delta - (152d delta + 730d delta)，方向暴露期限结构凸性",
        "mechanism": "273d-152d-730d delta 期限结构凸性，捕捉表面向近端或远端倾斜",
    },
    {
        "id": "econ_option.iv_30_360_velocity_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "multiply(divide(subtract({x}, {y}), {y}), sign(subtract({x}, ts_delay({x}, 22))))",
        "description": "IV 30d-360d velocity raw：(30d IV - 360d IV)/360d IV × sign(30d IV 22d change)，倒挂扩大速度",
        "mechanism": "仅倒挂 widening（22d 前端上升签名）携带信息，分离 genuine front-end repricing 与 parallel vol shift",
    },
    {
        "id": "econ_option.iv_60_273_neut_raw",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": False,
        "sign_allowed": True,
        "template": "vector_neut(divide({x}, {z}), divide({y}, {z}))",
        "description": "IV 60d/273d neutralized raw：60d/273d IV ratio neutralized vs 91d/273d leg，前端 vol 冲击正交化",
        "mechanism": "60d/273d IV 比率正交化 91d/273d 腿，隔离短端 vol 冲击",
    },
    {
        "id": "econ_option.vol_butterfly_250_rank_raw",
        "family": "econ_option",
        "n_fields": 3,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_rank(subtract(subtract({y}, {x}), subtract({z}, {y})), 252)",
        "description": "Vol butterfly 250d rank raw：(91d-60d)-(273d-91d) 250d ts_rank，表面 dislocation 长期排名",
        "mechanism": "期限结构凸性 250d ts_rank，捕捉表面 dislocation 相对长期历史",
    },
    {
        "id": "econ_option.gamma_vega_30_91_convexity_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Gamma-vega 30d/91d convexity raw：30d gamma / 91d vega，convexity per unit vol sensitivity",
        "mechanism": "30d gamma 相对 91d vega 的比率，捕捉 convexity per unit vol sensitivity",
    },
    {
        "id": "econ_option.forward_strike_122_moneyness_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Forward-strike 122d moneyness raw：122d forward / 122d strike，moneyness/carry 比率",
        "mechanism": "122d forward 相对 122d strike 的比率，捕捉 moneyness/carry 比率",
    },
    {
        "id": "econ_option.iv_91_365_std_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "divide(ts_std_dev({x}, 22), {y})",
        "description": "IV 91d std vs 365d level raw：std(91d IV,22) / 365d IV，implied vol 已实现波动相对长期水平",
        "mechanism": "91d IV 自身 22d 波动相对 365d IV 水平，捕捉 IV 移动速率",
    },
    {
        "id": "econ_option.delta_iv_182_91_corr_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_corr({x}, {y}, 66)",
        "description": "Delta-IV 182d-91d corr 66d raw：182d delta 与 91d IV 的 66d 相关，sticky-delta vs sticky-strike regime",
        "mechanism": "182d delta 与 91d IV 的 66d 相关，捕捉 sticky-delta vs sticky-strike regime",
    },
    {
        "id": "econ_option.premium_122_730_slope_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Premium 122d/730d slope raw：122d premium / 730d premium，权利金期限结构斜率",
        "mechanism": "122d premium 相对 730d premium 的比率，捕捉权利金期限结构斜率",
    },
    {
        "id": "econ_option.theta_60_182_ratio_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Theta 60d/182d ratio raw：60d theta / 182d theta，时间衰减期限结构比率",
        "mechanism": "60d theta 相对 182d theta 的比率，捕捉时间衰减期限结构比率",
    },
    {
        "id": "econ_option.delta_152_730_ratio_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": False,
        "sign_allowed": True,
        "template": "divide({x}, {y})",
        "description": "Delta 152d/730d ratio raw：152d delta / 730d delta，方向暴露期限结构比率",
        "mechanism": "152d delta 相对 730d delta 的比率，捕捉方向暴露期限结构比率",
    },
    {
        "id": "econ_option.iv_60_273_av_diff_raw",
        "family": "econ_option",
        "n_fields": 2,
        "needs_window": True,
        "sign_allowed": True,
        "template": "ts_av_diff(divide({x}, {y}), 66)",
        "description": "IV 60d/273d av-diff 66d raw：60d IV / 273d IV 66d 去均值，前端 vol 冲击相对自身历史",
        "mechanism": "60d IV 相对 273d IV 的比率 66d 去均值，捕捉前端 vol 冲击",
    },
]

