# -*- coding: utf-8 -*-
"""
operators_catalog.py — BRAIN platform operator catalog (fetched 2026-08-11 via get_operators, 102 operators).

Machine-readable reference for all skills. Each entry:
    name, category, scope (COMBO/REGULAR/SELECTION), definition, description, level

Categories: Arithmetic, Logical, Time Series, Cross Sectional, Vector,
            Transformational, Group, Special, Reduce
"""

OPERATORS = [
    # ── Arithmetic (16) ─────────────────────────────────────────────
    {"name": "add", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "add(x, y, filter=false), x + y",
     "description": "Adds two or more inputs element wise. filter=true treats NaNs as 0 before summing."},
    {"name": "multiply", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "multiply(x, y, ..., filter=false), x * y",
     "description": "Multiplies inputs element wise. filter=true treats NaNs as 0 before multiplication."},
    {"name": "sign", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "sign(x)",
     "description": "Returns +1 for positive, -1 for negative, 0 for zero; NaN if input NaN."},
    {"name": "subtract", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "subtract(x, y, filter=false), x - y",
     "description": "Subtracts inputs left to right. filter=true treats NaNs as 0."},
    {"name": "pasteurize", "category": "Arithmetic", "scope": ["COMBO", "REGULAR"],
     "definition": "pasteurize(x)",
     "description": "Set to NaN if x is INF or instrument not in Alpha universe. Reduces outliers."},
    {"name": "log", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "log(x)",
     "description": "Natural logarithm. For positive-valued data transforms."},
    {"name": "max", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "max(x, y, ..)",
     "description": "Maximum of all inputs. At least 2 inputs required."},
    {"name": "abs", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "abs(x)",
     "description": "Absolute value."},
    {"name": "divide", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "divide(x, y), x / y",
     "description": "x / y. Dividing by zero errors — use divide(x, add(y, 0.0001))."},
    {"name": "min", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "min(x, y ..)",
     "description": "Minimum of all inputs. At least 2 inputs required."},
    {"name": "signed_power", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "signed_power(x, y)",
     "description": "x^y preserving sign of x."},
    {"name": "inverse", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "inverse(x)",
     "description": "1/x. Errors at x=0 — use inverse(add(x, 0.0001))."},
    {"name": "sqrt", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "sqrt(x)",
     "description": "Non-negative sqrt. x<0 undefined — use signed_power(x, 0.5)."},
    {"name": "reverse", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "reverse(x)",
     "description": "-x. NOTE: counts as 1 operator in grammar (add(x,-y) is 8 ops vs subtract 6 ops)."},
    {"name": "power", "category": "Arithmetic", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "power(x, y)",
     "description": "x^y. Can drop sign for non-integer y — use signed_power to preserve."},
    {"name": "densify", "category": "Arithmetic", "scope": ["COMBO", "REGULAR"],
     "definition": "densify(x)",
     "description": "Reduces many group buckets to only available ones for efficiency."},

    # ── Logical (11) ────────────────────────────────────────────────
    {"name": "or", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "or(input1, input2)",
     "description": "1 if either input is 1, else 0."},
    {"name": "and", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "and(input1, input2)",
     "description": "1 if both inputs are 1, else 0."},
    {"name": "not", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "not(x)",
     "description": "Logical negation: 0 when x is 1, 1 when x is 0."},
    {"name": "is_nan", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "is_nan(input)",
     "description": "1 if input == NaN, else 0."},
    {"name": "less", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "input1 < input2",
     "description": "1 if input1 smaller than input2."},
    {"name": "equal", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "input1 == input2",
     "description": "1 if input1 == input2."},
    {"name": "greater", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "input1 > input2",
     "description": "1 if input1 larger than input2."},
    {"name": "if_else", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "if_else(input1, input2, input3)",
     "description": "Returns input2 if condition input1 true, else input3."},
    {"name": "not_equal", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "input1 != input2",
     "description": "1 if inputs differ."},
    {"name": "less_equal", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "input1 <= input2",
     "description": "1 if input1 <= input2."},
    {"name": "greater_equal", "category": "Logical", "scope": ["COMBO", "REGULAR", "SELECTION"],
     "definition": "input1 >= input2",
     "description": "1 if input1 >= input2."},

    # ── Time Series (30) ────────────────────────────────────────────
    {"name": "ts_corr", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_corr(x, y, d)",
     "description": "Pearson correlation of x and y over past d days."},
    {"name": "ts_zscore", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_zscore(x, d)",
     "description": "Z-score of time series: how far today's value from recent mean in std devs."},
    {"name": "ts_returns", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_returns(x, d, mode=1)",
     "description": "Relative change in x."},
    {"name": "ts_product", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_product(x, d)",
     "description": "Product of x over past d days. Geometric means / compounding."},
    {"name": "ts_std_dev", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_std_dev(x, d)",
     "description": "Std dev of x over past d days."},
    {"name": "ts_backfill", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_backfill(x, lookback=d, k=1)",
     "description": "Replaces NaN with most recent valid value within lookback. KEY for coverage gaps."},
    {"name": "days_from_last_change", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "days_from_last_change(x)",
     "description": "Days since last value change."},
    {"name": "last_diff_value", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "last_diff_value(x, d)",
     "description": "Most recent value of x from past d days different from current."},
    {"name": "ts_scale", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_scale(x, d, constant=0)",
     "description": "Scales series to 0-1 range by min/max over period."},
    {"name": "ts_step", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_step(1)",
     "description": "Day counter incrementing by 1 each day."},
    {"name": "ts_sum", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_sum(x, d)",
     "description": "Sum of x over past d days."},
    {"name": "ts_av_diff", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_av_diff(x, d)",
     "description": "x - ts_mean(x, d), ignoring NaN in mean."},
    {"name": "ts_kurtosis", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_kurtosis(x, d)",
     "description": "Kurtosis of x over last d days."},
    {"name": "ts_mean", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_mean(x, d)",
     "description": "Simple average of x over past d days. Primary smoothing operator."},
    {"name": "ts_arg_max", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_arg_max(x, d)",
     "description": "Days since max value in last d days."},
    {"name": "ts_rank", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_rank(x, d, constant=0)",
     "description": "Ranks current value among past d days (0-1). KEY trend operator."},
    {"name": "ts_ir", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_ir(x, d)",
     "description": "Information ratio = ts_mean(x, d) / ts_std_dev(x, d)."},
    {"name": "ts_delay", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_delay(x, d)",
     "description": "Value of x from d days ago."},
    {"name": "ts_quantile", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_quantile(x, d, driver='gaussian')",
     "description": "ts_rank transformed via inverse CDF of distribution."},
    {"name": "ts_count_nans", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_count_nans(x, d)",
     "description": "Count of NaN values over past d days."},
    {"name": "ts_covariance", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_covariance(y, x, d)",
     "description": "Covariance of y and x over past d days."},
    {"name": "ts_decay_linear", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_decay_linear(x, d, dense=false)",
     "description": "Linear decay smoothing over d days. KEY turnover reducer."},
    {"name": "ts_arg_min", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_arg_min(x, d)",
     "description": "Days since min value in last d days."},
    {"name": "ts_regression", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_regression(y, x, d, lag=0, rettype=0)",
     "description": "Regression parameters over d days. NOTE: .residual suffix INVALID syntax."},
    {"name": "ts_max_diff", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_max_diff(x, d)",
     "description": "x - ts_max(x, d)."},
    {"name": "kth_element", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "kth_element(x, d, k, ignore='NaN')",
     "description": "K-th value looking back d days. Backtest event windows."},
    {"name": "hump", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "hump(x, hump=0.01)",
     "description": "Limits change magnitude, reducing turnover. WARNING: destructive on combos."},
    {"name": "ts_delta", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_delta(x, d)",
     "description": "x - ts_delay(x, d). Momentum/change measure. KEY momentum operator."},
    {"name": "ts_target_tvr_decay", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_target_tvr_decay(x, lambda_min=0, lambda_max=1, target_tvr=0.1)",
     "description": "Tune ts_decay to target turnover."},
    {"name": "ts_target_tvr_hump", "category": "Time Series", "scope": ["COMBO", "REGULAR"],
     "definition": "ts_target_tvr_hump(x, lambda_min=0, lambda_max=1, target_tvr=0.1)",
     "description": "Tune hump to target turnover."},

    # ── Cross Sectional (6) ─────────────────────────────────────────
    {"name": "winsorize", "category": "Cross Sectional", "scope": ["COMBO", "REGULAR"],
     "definition": "winsorize(x, std=4)",
     "description": "Limits values to std devs from mean. KEY outlier reducer."},
    {"name": "rank", "category": "Cross Sectional", "scope": ["COMBO", "REGULAR"],
     "definition": "rank(x, rate=2)",
     "description": "Ranks across instruments, evenly spaced 0-1. KEY normalization."},
    {"name": "zscore", "category": "Cross Sectional", "scope": ["COMBO", "REGULAR"],
     "definition": "zscore(x)",
     "description": "Cross-sectional z-score vs mean of group."},
    {"name": "scale", "category": "Cross Sectional", "scope": ["COMBO", "REGULAR"],
     "definition": "scale(x, scale=1, longscale=1, shortscale=1)",
     "description": "Scales sum of |values| to book size. Separate long/short scaling."},
    {"name": "normalize", "category": "Cross Sectional", "scope": ["COMBO", "REGULAR"],
     "definition": "normalize(x, useStd=false, limit=0.0)",
     "description": "Centers daily cross section by market mean; optional std division + clamp."},
    {"name": "quantile", "category": "Cross Sectional", "scope": ["COMBO", "REGULAR"],
     "definition": "quantile(x, driver=gaussian, sigma=1.0)",
     "description": "Ranks + shifts alpha, applies distribution (gaussian/cauchy/uniform) to reduce outliers."},

    # ── Vector (7) ──────────────────────────────────────────────────
    {"name": "vec_min", "category": "Vector", "scope": ["COMBO", "REGULAR"],
     "definition": "vec_min(x)",
     "description": "Minimum value of vector field."},
    {"name": "vec_count", "category": "Vector", "scope": ["COMBO", "REGULAR"],
     "definition": "vec_count(x)",
     "description": "Number of elements in vector field."},
    {"name": "vec_sum", "category": "Vector", "scope": ["COMBO", "REGULAR"],
     "definition": "vec_sum(x)",
     "description": "Sum of all values in vector field."},
    {"name": "vec_max", "category": "Vector", "scope": ["COMBO", "REGULAR"],
     "definition": "vec_max(x)",
     "description": "Maximum value of vector field."},
    {"name": "vec_avg", "category": "Vector", "scope": ["COMBO", "REGULAR"],
     "definition": "vec_avg(x)",
     "description": "Mean of vector elements per instrument/date. KEY vector→matrix aggregation."},
    {"name": "vec_stddev", "category": "Vector", "scope": ["COMBO", "REGULAR"],
     "definition": "vec_stddev(x)",
     "description": "Std dev of vector field."},
    {"name": "vec_range", "category": "Vector", "scope": ["COMBO", "REGULAR"],
     "definition": "vec_range(x)",
     "description": "max - min of vector field."},

    # ── Transformational (4) ────────────────────────────────────────
    {"name": "bucket", "category": "Transformational", "scope": ["COMBO", "REGULAR"],
     "definition": "bucket(rank(x), range='0,1,0.1', skipBoth=False, NaNGroup=False) or bucket(rank(x), buckets='2,5,6,7,10', ...)",
     "description": "Creates custom groups from ranked values. Used with group ops."},
    {"name": "tail", "category": "Transformational", "scope": ["COMBO", "REGULAR"],
     "definition": "tail(x, lower=0, upper=0, newval=0)",
     "description": "If lower < x < upper return newval else x."},
    {"name": "trade_when", "category": "Transformational", "scope": ["COMBO", "REGULAR"],
     "definition": "trade_when(x, y, z)",
     "description": "Changes alpha values only when condition met; keeps previous otherwise."},
    {"name": "generate_stats", "category": "Transformational", "scope": ["COMBO"],
     "definition": "generate_stats(alpha)",
     "description": "Calculates alpha statistics per day in IS period (COMBO only)."},

    # ── Group (11) ──────────────────────────────────────────────────
    {"name": "group_mean", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_mean(x, weight, group)",
     "description": "Harmonic mean within each group."},
    {"name": "group_rank", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_rank(x, group)",
     "description": "Ranks within group (0-1). KEY country/sector normalization."},
    {"name": "group_backfill", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_backfill(x, group, d, std=4.0)",
     "description": "Fills NaN with winsorized group mean over past d days."},
    {"name": "group_scale", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_scale(x, group)",
     "description": "Normalizes values within group to 0-1."},
    {"name": "group_count", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_count(x, group)",
     "description": "Number of instruments in group with valid x."},
    {"name": "group_zscore", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_zscore(x, group)",
     "description": "Z-score within group vs group mean/std."},
    {"name": "group_std_dev", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_std_dev(x, group)",
     "description": "Group std dev broadcast to all elements."},
    {"name": "group_sum", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_sum(x, group)",
     "description": "Sum of x within group."},
    {"name": "group_neutralize", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_neutralize(x, group)",
     "description": "Subtract group mean from each value. KEY sector/industry neutralization."},
    {"name": "group_cartesian_product", "category": "Group", "scope": ["COMBO", "REGULAR"],
     "definition": "group_cartesian_product(g1, g2)",
     "description": "Merge two groups: len_1 × len_2 indices."},
    {"name": "combo_a", "category": "Group", "scope": ["COMBO"],
     "definition": "combo_a(alpha, nlength=250, mode='algo1')",
     "description": "Combines multiple alpha signals balancing return vs variability (COMBO only)."},

    # ── Special (3) ─────────────────────────────────────────────────
    {"name": "self_corr", "category": "Special", "scope": ["COMBO"],
     "definition": "self_corr(input)",
     "description": "Correlation matrix over lookback K (COMBO only)."},
    {"name": "in", "category": "Special", "scope": ["SELECTION"],
     "definition": "in",
     "description": "Membership test (SELECTION only)."},
    {"name": "universe_size", "category": "Special", "scope": ["SELECTION"],
     "definition": "universe_size",
     "description": "Universe size (SELECTION only)."},

    # ── Reduce (14) — COMBO only ────────────────────────────────────
    {"name": "reduce_ir", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_ir(input)",
     "description": "IR of values in the array (COMBO)."},
    {"name": "reduce_avg", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_avg(input, threshold=0)",
     "description": "Average of non-NaN elements; threshold = min valid count (COMBO)."},
    {"name": "reduce_powersum", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_powersum(input, constant=2, precise=false)",
     "description": "Sum of power(x, constant) (COMBO)."},
    {"name": "reduce_max", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_max(input)",
     "description": "Max of elements (COMBO)."},
    {"name": "reduce_min", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_min(input)",
     "description": "Min of elements (COMBO)."},
    {"name": "reduce_norm", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_norm(input)",
     "description": "Absolute sum of elements (COMBO)."},
    {"name": "reduce_sum", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_sum(input)",
     "description": "Sum of elements (COMBO)."},
    {"name": "reduce_range", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_range(input)",
     "description": "Range of values; NaN if none valid (COMBO)."},
    {"name": "reduce_percentage", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_percentage(input, percentage=0.5)",
     "description": "Value at sorted percentile; median at 0.5 (COMBO)."},
    {"name": "reduce_skewness", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_skewness(input)",
     "description": "Skewness of values (COMBO)."},
    {"name": "reduce_count", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_count(input, threshold)",
     "description": "Count elements > threshold (COMBO)."},
    {"name": "reduce_kurtosis", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_kurtosis(input)",
     "description": "Kurtosis of values (COMBO)."},
    {"name": "reduce_choose", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_choose(input, nth, ignoreNan=true)",
     "description": "Choose nth element; NaN if not found (COMBO)."},
    {"name": "reduce_stddev", "category": "Reduce", "scope": ["COMBO"],
     "definition": "reduce_stddev(input, threshold=0)",
     "description": "Std dev of values; threshold = min valid % (COMBO)."},
]

# Convenience indexes
BY_NAME = {op["name"]: op for op in OPERATORS}
REGULAR_OPS = [op for op in OPERATORS if "REGULAR" in op["scope"]]
COMBO_OPS = [op for op in OPERATORS if "COMBO" in op["scope"]]
SELECTION_OPS = [op for op in OPERATORS if "SELECTION" in op["scope"]]
VECTOR_OPS = [op["name"] for op in OPERATORS if op["category"] == "Vector"]
TIME_SERIES_OPS = [op["name"] for op in OPERATORS if op["category"] == "Time Series"]
GROUP_OPS = [op["name"] for op in OPERATORS if op["category"] == "Group"]
CROSS_SECTIONAL_OPS = [op["name"] for op in OPERATORS if op["category"] == "Cross Sectional"]
ARITHMETIC_OPS = [op["name"] for op in OPERATORS if op["category"] == "Arithmetic"]
LOGICAL_OPS = [op["name"] for op in OPERATORS if op["category"] == "Logical"]

# Operators verified usable in REGULAR alphas (from glb_alpha_machine /ops API, 2026-08-08)
# NOTE: group_normalize NOT available; ts_skewness/ts_entropy NOT available; vec_ts_rank NOT available.
REGULAR_VERIFIED = [
    # basic
    "log", "sqrt", "reverse", "inverse", "rank", "zscore", "quantile", "normalize",
    # ts
    "ts_rank", "ts_zscore", "ts_delta", "ts_sum", "ts_product", "ts_ir", "ts_std_dev",
    "ts_mean", "ts_arg_min", "ts_arg_max", "ts_max_diff", "ts_returns", "ts_scale",
    "ts_kurtosis", "ts_quantile",
    # arsenal
    "signed_power",
    # group
    "group_rank",
]

SECOND_GROUP_OPS = ["group_neutralize", "group_rank", "group_scale", "group_zscore"]

# Group dimensions verified available for GLB (2026-08-08)
GROUP_DIMS_VERIFIED = ["market", "sector", "industry", "subindustry"]
GROUP_DIMS_FORMULA = [
    "bucket(rank(cap), range='0.1,1,0.1')",
    "bucket(group_rank(cap, sector), range='0,1,0.1')",
    "bucket(rank(ts_std_dev(ts_returns(close, 1), 20)), range='0.1,1,0.1')",
]


if __name__ == "__main__":
    import json
    print(f"Total operators: {len(OPERATORS)}")
    print(f"  REGULAR: {len(REGULAR_OPS)} | COMBO: {len(COMBO_OPS)} | SELECTION: {len(SELECTION_OPS)}")
    print(f"  Verified REGULAR (glb pipeline): {len(REGULAR_VERIFIED)}")
    print("\nCategories:")
    cats = {}
    for op in OPERATORS:
        cats.setdefault(op["category"], 0)
        cats[op["category"]] += 1
    for c, n in cats.items():
        print(f"  {c}: {n}")